/**
 * Shapes returned by the database. Kept hand-written and small so the app has
 * one obvious place to look for "what does a row look like".
 *
 * These are `type` aliases, not `interface`s, and that is load-bearing:
 * postgrest-js requires every `Row` to satisfy `Record<string, unknown>`, and
 * TypeScript only gives implicit index signatures to type aliases. Switching
 * any of them to `interface` makes `Database["public"]` stop matching
 * `GenericSchema`, at which point every query silently resolves to `never`.
 */

export type BillStatus = "pending" | "partially_paid" | "paid";

export type Project = {
  id: string;
  project_name: string;
  client_name: string;
  location: string;
  start_date: string | null;
  contract_value: number;
  description: string;
  created_at: string;
  updated_at: string;
};

/** One row of the `project_financials` view — every dashboard number. */
export type ProjectFinancials = {
  project_id: string;
  project_name: string;
  client_name: string;
  location: string;
  start_date: string | null;
  contract_value: number;
  description: string;
  created_at: string;
  updated_at: string;
  total_expenses: number;
  expense_days: number;
  total_advance_received: number;
  remaining_advance: number;
  total_billed: number;
  total_billing_received: number;
  outstanding_billing: number;
  bill_count: number;
};

export type DailyExpense = {
  id: string;
  project_id: string;
  expense_date: string;
  material: string;
  price: number;
  created_at: string;
  updated_at: string;
};

/** One row of the `daily_expense_totals` view — one expense page. */
export type DailyExpenseTotal = {
  project_id: string;
  expense_date: string;
  line_count: number;
  daily_total: number;
};

export type Advance = {
  id: string;
  project_id: string;
  payment_date: string;
  amount: number;
  notes: string;
  created_at: string;
};

export type ProgressBill = {
  id: string;
  project_id: string;
  bill_number: string;
  bill_date: string;
  work_description: string;
  progress_percentage: number;
  bill_amount: number;
  amount_received: number;
  status: BillStatus;
  notes: string;
  created_at: string;
};

/**
 * Minimal typing for the supabase-js generics.
 *
 * `Relationships` is required on every table and view by postgrest-js's
 * `GenericTable` / `GenericView`. The arrays are empty because this app never
 * uses PostgREST's embedded-resource joins — it joins in SQL, inside the views.
 *
 * The two views are declared read-only (Row + Relationships, no Insert or
 * Update), which matches `GenericNonUpdatableView` and turns an accidental
 * write to a view into a compile error.
 */
export type Database = {
  public: {
    Tables: {
      projects: {
        Row: Project;
        Insert: Partial<Project> & { project_name: string };
        Update: Partial<Project>;
        Relationships: [];
      };
      daily_expenses: {
        Row: DailyExpense;
        Insert: Partial<DailyExpense> & {
          project_id: string;
          expense_date: string;
          material: string;
          price: number;
        };
        Update: Partial<DailyExpense>;
        Relationships: [];
      };
      advances: {
        Row: Advance;
        Insert: Partial<Advance> & { project_id: string; amount: number };
        Update: Partial<Advance>;
        Relationships: [];
      };
      progress_bills: {
        Row: ProgressBill;
        // `status` is generated by the database, so it is never written.
        Insert: Omit<Partial<ProgressBill>, "status"> & {
          project_id: string;
          bill_number: string;
        };
        Update: Omit<Partial<ProgressBill>, "status">;
        Relationships: [];
      };
    };
    Views: {
      project_financials: { Row: ProjectFinancials; Relationships: [] };
      daily_expense_totals: { Row: DailyExpenseTotal; Relationships: [] };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
